---
name: Generate Diagrams
on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install diagrams

      - working-directory: diagrams
        run: ./generate.sh

      - name: Commit images
        uses: test-room-7/action-update-file@v1
        with:
          file-path: diagrams/*.png
          commit-msg: generated diagrams
          github-token: ${{ secrets.GITHUB_TOKEN }}
